apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://localhost:3200
    isDefault: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
      nodeGraph:
        enabled: true

  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    uid: loki
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: "traceId=(\\w+)"
          url: "$${__value.raw}"
          datasourceUid: tempo

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
